export interface ThemeVars {
    '--bg-primary': string;
    '--bg-secondary': string;
    '--bg-sidebar': string;
    '--bg-titlebar': string;
    '--bg-statusbar': string;
    '--bg-hover': string;
    '--bg-active': string;
    '--border': string;
    '--text-primary': string;
    '--text-secondary': string;
    '--text-dim': string;
    '--text-sidebar': string;
    '--text-active': string;
    '--line-number': string;
    '--cursor': string;
    '--selection': string;
    '--accent': string;
    '--accent-hover': string;
    '--scrollbar': string;
    '--scrollbar-hover': string;
}

export interface Theme {
    id: string;
    name: string;
    isDark: boolean;
    vars: ThemeVars;
}

export const themes: Theme[] = [
    {
        id: 'default-dark',
        name: 'Default Dark',
        isDark: true,
        vars: {
            '--bg-primary': '#1e1e1e',
            '--bg-secondary': '#252526',
            '--bg-sidebar': '#2d2d2d',
            '--bg-titlebar': '#3c3c3c',
            '--bg-statusbar': '#007acc',
            '--bg-hover': '#2a2d2e',
            '--bg-active': '#37373d',
            '--border': '#3e3e42',
            '--text-primary': '#d4d4d4',
            '--text-secondary': '#858585',
            '--text-dim': '#6b6b6b',
            '--text-sidebar': '#cccccc',
            '--text-active': '#ffffff',
            '--line-number': '#5a5a5a',
            '--cursor': '#aeafad',
            '--selection': '#264f78',
            '--accent': '#4fc1ff',
            '--accent-hover': '#3aabea',
            '--scrollbar': '#424242',
            '--scrollbar-hover': '#555555',
        },
    },
    {
        id: 'default-light',
        name: 'Default Light',
        isDark: false,
        vars: {
            '--bg-primary': '#ffffff',
            '--bg-secondary': '#f3f3f3',
            '--bg-sidebar': '#e8e8e8',
            '--bg-titlebar': '#dddddd',
            '--bg-statusbar': '#007acc',
            '--bg-hover': '#e8eeee',
            '--bg-active': '#d6d6d6',
            '--border': '#e5e7eb',
            '--text-primary': '#111827',
            '--text-secondary': '#6b7280',
            '--text-dim': '#9ca3af',
            '--text-sidebar': '#374151',
            '--text-active': '#000000',
            '--line-number': '#9ca3af',
            '--cursor': '#374151',
            '--selection': '#bfdbfe',
            '--accent': '#3b82f6',
            '--accent-hover': '#2563eb',
            '--scrollbar': '#d1d5db',
            '--scrollbar-hover': '#9ca3af',
        },
    },
    {
        id: 'midnight',
        name: 'Midnight',
        isDark: true,
        vars: {
            '--bg-primary': '#1e1e2e',
            '--bg-secondary': '#2a2a3d',
            '--bg-sidebar': '#181825',
            '--bg-titlebar': '#313244',
            '--bg-statusbar': '#45475a',
            '--bg-hover': '#313244',
            '--bg-active': '#45475a',
            '--border': '#3a3a5c',
            '--text-primary': '#cdd6f4',
            '--text-secondary': '#6c7086',
            '--text-dim': '#585b70',
            '--text-sidebar': '#cdd6f4',
            '--text-active': '#ffffff',
            '--line-number': '#585b70',
            '--cursor': '#f5e0dc',
            '--selection': '#3a3a5c',
            '--accent': '#89b4fa',
            '--accent-hover': '#74a8f6',
            '--scrollbar': '#45475a',
            '--scrollbar-hover': '#585b70',
        },
    },
    {
        id: 'nord',
        name: 'Nord',
        isDark: true,
        vars: {
            '--bg-primary': '#2e3440',
            '--bg-secondary': '#3b4252',
            '--bg-sidebar': '#272c36',
            '--bg-titlebar': '#434c5e',
            '--bg-statusbar': '#5e81ac',
            '--bg-hover': '#434c5e',
            '--bg-active': '#4c566a',
            '--border': '#434c5e',
            '--text-primary': '#eceff4',
            '--text-secondary': '#9099a7',
            '--text-dim': '#767e8c',
            '--text-sidebar': '#d8dee9',
            '--text-active': '#eceff4',
            '--line-number': '#767e8c',
            '--cursor': '#d8dee9',
            '--selection': '#4c566a',
            '--accent': '#88c0d0',
            '--accent-hover': '#7ab1c2',
            '--scrollbar': '#4c566a',
            '--scrollbar-hover': '#5e6a7a',
        },
    },
    {
        id: 'solarized-light',
        name: 'Solarized Light',
        isDark: false,
        vars: {
            '--bg-primary': '#fdf6e3',
            '--bg-secondary': '#eee8d5',
            '--bg-sidebar': '#e8e2cc',
            '--bg-titlebar': '#ddd5b8',
            '--bg-statusbar': '#268bd2',
            '--bg-hover': '#e8e2cc',
            '--bg-active': '#d4cdb7',
            '--border': '#d4cdb7',
            '--text-primary': '#657b83',
            '--text-secondary': '#93a1a1',
            '--text-dim': '#aab1b1',
            '--text-sidebar': '#586e75',
            '--text-active': '#002b36',
            '--line-number': '#aab1b1',
            '--cursor': '#657b83',
            '--selection': '#bee3f8',
            '--accent': '#268bd2',
            '--accent-hover': '#1f75b2',
            '--scrollbar': '#c1b8a2',
            '--scrollbar-hover': '#a8a090',
        },
    },
    {
        id: 'tokyo-night',
        name: 'Tokyo Night',
        isDark: true,
        vars: {
            '--bg-primary': '#1a1b26',
            '--bg-secondary': '#24283b',
            '--bg-sidebar': '#16161e',
            '--bg-titlebar': '#2f334d',
            '--bg-statusbar': '#3d59a1',
            '--bg-hover': '#2f334d',
            '--bg-active': '#414868',
            '--border': '#414868',
            '--text-primary': '#c0caf5',
            '--text-secondary': '#565f89',
            '--text-dim': '#444b6a',
            '--text-sidebar': '#a9b1d6',
            '--text-active': '#c0caf5',
            '--line-number': '#444b6a',
            '--cursor': '#c0caf5',
            '--selection': '#283457',
            '--accent': '#7dcfff',
            '--accent-hover': '#65c2f8',
            '--scrollbar': '#414868',
            '--scrollbar-hover': '#565f89',
        },
    },
    {
        id: 'monokai',
        name: 'Monokai',
        isDark: true,
        vars: {
            '--bg-primary': '#272822',
            '--bg-secondary': '#3e3d32',
            '--bg-sidebar': '#1e1f1b',
            '--bg-titlebar': '#3e3d32',
            '--bg-statusbar': '#75715e',
            '--bg-hover': '#49483e',
            '--bg-active': '#555449',
            '--border': '#555549',
            '--text-primary': '#f8f8f2',
            '--text-secondary': '#75715e',
            '--text-dim': '#5c5a50',
            '--text-sidebar': '#f8f8f2',
            '--text-active': '#f8f8f2',
            '--line-number': '#5c5a50',
            '--cursor': '#f8f8f0',
            '--selection': '#49483e',
            '--accent': '#a6e22e',
            '--accent-hover': '#94d61c',
            '--scrollbar': '#555549',
            '--scrollbar-hover': '#666658',
        },
    },
    {
        id: 'dracula',
        name: 'Dracula',
        isDark: true,
        vars: {
            '--bg-primary': '#282a36',
            '--bg-secondary': '#343746',
            '--bg-sidebar': '#21222c',
            '--bg-titlebar': '#44475a',
            '--bg-statusbar': '#6272a4',
            '--bg-hover': '#44475a',
            '--bg-active': '#6272a4',
            '--border': '#44475a',
            '--text-primary': '#f8f8f2',
            '--text-secondary': '#6272a4',
            '--text-dim': '#4d5470',
            '--text-sidebar': '#f8f8f2',
            '--text-active': '#ffffff',
            '--line-number': '#4d5470',
            '--cursor': '#f8f8f2',
            '--selection': '#44475a',
            '--accent': '#ff79c6',
            '--accent-hover': '#ff5fbc',
            '--scrollbar': '#44475a',
            '--scrollbar-hover': '#6272a4',
        },
    },
    {
        id: 'one-dark-pro',
        name: 'One Dark Pro',
        isDark: true,
        vars: {
            '--bg-primary': '#282c34',
            '--bg-secondary': '#2c313c',
            '--bg-sidebar': '#21252b',
            '--bg-titlebar': '#3e4451',
            '--bg-statusbar': '#4078f2',
            '--bg-hover': '#3e4451',
            '--bg-active': '#4b5263',
            '--border': '#3e4451',
            '--text-primary': '#abb2bf',
            '--text-secondary': '#5c6370',
            '--text-dim': '#4b5263',
            '--text-sidebar': '#abb2bf',
            '--text-active': '#ffffff',
            '--line-number': '#4b5263',
            '--cursor': '#528bff',
            '--selection': '#3e4451',
            '--accent': '#61afef',
            '--accent-hover': '#4d9fdf',
            '--scrollbar': '#3e4451',
            '--scrollbar-hover': '#4b5263',
        },
    },
    {
        id: 'gruvbox-dark',
        name: 'Gruvbox Dark',
        isDark: true,
        vars: {
            '--bg-primary': '#282828',
            '--bg-secondary': '#3c3836',
            '--bg-sidebar': '#1d2021',
            '--bg-titlebar': '#504945',
            '--bg-statusbar': '#504945',
            '--bg-hover': '#504945',
            '--bg-active': '#665c54',
            '--border': '#504945',
            '--text-primary': '#ebdbb2',
            '--text-secondary': '#928374',
            '--text-dim': '#7c6f64',
            '--text-sidebar': '#ebdbb2',
            '--text-active': '#fbf1c7',
            '--line-number': '#7c6f64',
            '--cursor': '#ebdbb2',
            '--selection': '#504945',
            '--accent': '#fabd2f',
            '--accent-hover': '#e8b020',
            '--scrollbar': '#504945',
            '--scrollbar-hover': '#665c54',
        },
    },
    {
        id: 'synthwave',
        name: 'Synthwave',
        isDark: true,
        vars: {
            '--bg-primary': '#1a1333',
            '--bg-secondary': '#241b4d',
            '--bg-sidebar': '#130e27',
            '--bg-titlebar': '#2e2460',
            '--bg-statusbar': '#3d2b6b',
            '--bg-hover': '#2e2460',
            '--bg-active': '#3d2b6b',
            '--border': '#3d2b6b',
            '--text-primary': '#ffffff',
            '--text-secondary': '#9d8ec7',
            '--text-dim': '#6b5f99',
            '--text-sidebar': '#ffffff',
            '--text-active': '#ffffff',
            '--line-number': '#6b5f99',
            '--cursor': '#ff2d78',
            '--selection': '#3d2b6b',
            '--accent': '#ff2d78',
            '--accent-hover': '#e01f65',
            '--scrollbar': '#3d2b6b',
            '--scrollbar-hover': '#4e3880',
        },
    },
    {
        id: 'matrix',
        name: 'Matrix',
        isDark: true,
        vars: {
            '--bg-primary': '#0d0d0d',
            '--bg-secondary': '#1a1a1a',
            '--bg-sidebar': '#080808',
            '--bg-titlebar': '#1f3d1f',
            '--bg-statusbar': '#1f3d1f',
            '--bg-hover': '#1f3d1f',
            '--bg-active': '#2a5c2a',
            '--border': '#1f3d1f',
            '--text-primary': '#00ff41',
            '--text-secondary': '#008f11',
            '--text-dim': '#005c0a',
            '--text-sidebar': '#00ff41',
            '--text-active': '#00ff41',
            '--line-number': '#005c0a',
            '--cursor': '#00ff41',
            '--selection': '#1f3d1f',
            '--accent': '#00ff41',
            '--accent-hover': '#00cc33',
            '--scrollbar': '#1f3d1f',
            '--scrollbar-hover': '#2a5c2a',
        },
    },
    {
        id: 'amber-terminal',
        name: 'Amber Terminal',
        isDark: true,
        vars: {
            '--bg-primary': '#0d0a00',
            '--bg-secondary': '#1a1400',
            '--bg-sidebar': '#080600',
            '--bg-titlebar': '#2e2200',
            '--bg-statusbar': '#2e2200',
            '--bg-hover': '#2e2200',
            '--bg-active': '#3d2e00',
            '--border': '#2e2200',
            '--text-primary': '#ffb300',
            '--text-secondary': '#7a5500',
            '--text-dim': '#503800',
            '--text-sidebar': '#ffb300',
            '--text-active': '#ffcc00',
            '--line-number': '#503800',
            '--cursor': '#ffb300',
            '--selection': '#2e2200',
            '--accent': '#ffcc00',
            '--accent-hover': '#e6b800',
            '--scrollbar': '#2e2200',
            '--scrollbar-hover': '#3d2e00',
        },
    },
    {
        id: 'forest',
        name: 'Forest',
        isDark: true,
        vars: {
            '--bg-primary': '#1a2318',
            '--bg-secondary': '#243022',
            '--bg-sidebar': '#121a10',
            '--bg-titlebar': '#2d3f2a',
            '--bg-statusbar': '#344d30',
            '--bg-hover': '#2d3f2a',
            '--bg-active': '#344d30',
            '--border': '#344d30',
            '--text-primary': '#d4e6c3',
            '--text-secondary': '#6b8f5e',
            '--text-dim': '#4a6640',
            '--text-sidebar': '#d4e6c3',
            '--text-active': '#e8f5d8',
            '--line-number': '#4a6640',
            '--cursor': '#d4e6c3',
            '--selection': '#344d30',
            '--accent': '#7ec850',
            '--accent-hover': '#6ab840',
            '--scrollbar': '#344d30',
            '--scrollbar-hover': '#4a6640',
        },
    },
    {
        id: 'ocean',
        name: 'Ocean',
        isDark: true,
        vars: {
            '--bg-primary': '#0a1628',
            '--bg-secondary': '#112240',
            '--bg-sidebar': '#060e1c',
            '--bg-titlebar': '#1d3461',
            '--bg-statusbar': '#1d3461',
            '--bg-hover': '#1d3461',
            '--bg-active': '#254480',
            '--border': '#1d3461',
            '--text-primary': '#ccd6f6',
            '--text-secondary': '#5a7a9f',
            '--text-dim': '#3a5470',
            '--text-sidebar': '#ccd6f6',
            '--text-active': '#e8eeff',
            '--line-number': '#3a5470',
            '--cursor': '#ccd6f6',
            '--selection': '#1d3461',
            '--accent': '#64ffda',
            '--accent-hover': '#4decca',
            '--scrollbar': '#1d3461',
            '--scrollbar-hover': '#254480',
        },
    },
];

export const DEFAULT_THEME_ID = 'default-dark';

export function getTheme(id: string): Theme {
    return themes.find((t) => t.id === id) ?? themes[0];
}
