export interface ThemeVars {
    '--bg-primary': string;
    '--bg-secondary': string;
    '--bg-sidebar': string;
    '--bg-titlebar': string;
    '--bg-statusbar': string;
    '--bg-hover': string;
    '--bg-active': string;
    '--border': string;
    '--text-primary': string;
    '--text-secondary': string;
    '--text-dim': string;
    '--text-sidebar': string;
    '--text-active': string;
    '--line-number': string;
    '--cursor': string;
    '--selection': string;
    '--accent': string;
    '--accent-hover': string;
    '--scrollbar': string;
    '--scrollbar-hover': string;
}

export interface Theme {
    id: string;
    name: string;
    isDark: boolean;
    vars: ThemeVars;
}

export const themes: Theme[] = [
    {
        id: 'default-dark',
        name: 'Default Dark',
        isDark: true,
        vars: {
            '--bg-primary': '#1e1e1e',
            '--bg-secondary': '#252526',
            '--bg-sidebar': '#2d2d2d',
            '--bg-titlebar': '#3c3c3c',
            '--bg-statusbar': '#007acc',
            '--bg-hover': '#2a2d2e',
            '--bg-active': '#37373d',
            '--border': '#3e3e42',
            '--text-primary': '#d4d4d4',
            '--text-secondary': '#858585',
            '--text-dim': '#6b6b6b',
            '--text-sidebar': '#cccccc',
            '--text-active': '#ffffff',
            '--line-number': '#5a5a5a',
            '--cursor': '#aeafad',
            '--selection': '#264f78',
            '--accent': '#4fc1ff',
            '--accent-hover': '#3aabea',
            '--scrollbar': '#424242',
            '--scrollbar-hover': '#555555',
        },
    },
    {
        id: 'midnight',
        name: 'Midnight',
        isDark: true,
        vars: {
            '--bg-primary': '#1e1e2e',
            '--bg-secondary': '#2a2a3d',
            '--bg-sidebar': '#181825',
            '--bg-titlebar': '#313244',
            '--bg-statusbar': '#45475a',
            '--bg-hover': '#313244',
            '--bg-active': '#45475a',
            '--border': '#3a3a5c',
            '--text-primary': '#cdd6f4',
            '--text-secondary': '#6c7086',
            '--text-dim': '#585b70',
            '--text-sidebar': '#cdd6f4',
            '--text-active': '#ffffff',
            '--line-number': '#585b70',
            '--cursor': '#f5e0dc',
            '--selection': '#3a3a5c',
            '--accent': '#89b4fa',
            '--accent-hover': '#74a8f6',
            '--scrollbar': '#45475a',
            '--scrollbar-hover': '#585b70',
        },
    },
    {
        id: 'nord',
        name: 'Nord',
        isDark: true,
        vars: {
            '--bg-primary': '#2e3440',
            '--bg-secondary': '#3b4252',
            '--bg-sidebar': '#272c36',
            '--bg-titlebar': '#434c5e',
            '--bg-statusbar': '#5e81ac',
            '--bg-hover': '#434c5e',
            '--bg-active': '#4c566a',
            '--border': '#434c5e',
            '--text-primary': '#eceff4',
            '--text-secondary': '#9099a7',
            '--text-dim': '#767e8c',
            '--text-sidebar': '#d8dee9',
            '--text-active': '#eceff4',
            '--line-number': '#767e8c',
            '--cursor': '#d8dee9',
            '--selection': '#4c566a',
            '--accent': '#88c0d0',
            '--accent-hover': '#7ab1c2',
            '--scrollbar': '#4c566a',
            '--scrollbar-hover': '#5e6a7a',
        },
    },
    {
        id: 'tokyo-night',
        name: 'Tokyo Night',
        isDark: true,
        vars: {
            '--bg-primary': '#1a1b26',
            '--bg-secondary': '#24283b',
            '--bg-sidebar': '#16161e',
            '--bg-titlebar': '#2f334d',
            '--bg-statusbar': '#3d59a1',
            '--bg-hover': '#2f334d',
            '--bg-active': '#414868',
            '--border': '#414868',
            '--text-primary': '#c0caf5',
            '--text-secondary': '#565f89',
            '--text-dim': '#444b6a',
            '--text-sidebar': '#a9b1d6',
            '--text-active': '#c0caf5',
            '--line-number': '#444b6a',
            '--cursor': '#c0caf5',
            '--selection': '#283457',
            '--accent': '#7dcfff',
            '--accent-hover': '#65c2f8',
            '--scrollbar': '#414868',
            '--scrollbar-hover': '#565f89',
        },
    },
    {
        id: 'one-dark-pro',
        name: 'One Dark Pro',
        isDark: true,
        vars: {
            '--bg-primary': '#282c34',
            '--bg-secondary': '#2c313c',
            '--bg-sidebar': '#21252b',
            '--bg-titlebar': '#3e4451',
            '--bg-statusbar': '#4078f2',
            '--bg-hover': '#3e4451',
            '--bg-active': '#4b5263',
            '--border': '#3e4451',
            '--text-primary': '#abb2bf',
            '--text-secondary': '#5c6370',
            '--text-dim': '#4b5263',
            '--text-sidebar': '#abb2bf',
            '--text-active': '#ffffff',
            '--line-number': '#4b5263',
            '--cursor': '#528bff',
            '--selection': '#3e4451',
            '--accent': '#61afef',
            '--accent-hover': '#4d9fdf',
            '--scrollbar': '#3e4451',
            '--scrollbar-hover': '#4b5263',
        },
    },
    {
        id: 'gruvbox-dark',
        name: 'Gruvbox Dark',
        isDark: true,
        vars: {
            '--bg-primary': '#282828',
            '--bg-secondary': '#3c3836',
            '--bg-sidebar': '#1d2021',
            '--bg-titlebar': '#504945',
            '--bg-statusbar': '#504945',
            '--bg-hover': '#504945',
            '--bg-active': '#665c54',
            '--border': '#504945',
            '--text-primary': '#ebdbb2',
            '--text-secondary': '#928374',
            '--text-dim': '#7c6f64',
            '--text-sidebar': '#ebdbb2',
            '--text-active': '#fbf1c7',
            '--line-number': '#7c6f64',
            '--cursor': '#ebdbb2',
            '--selection': '#504945',
            '--accent': '#fabd2f',
            '--accent-hover': '#e8b020',
            '--scrollbar': '#504945',
            '--scrollbar-hover': '#665c54',
        },
    },
    {
        id: 'forest',
        name: 'Forest',
        isDark: true,
        vars: {
            '--bg-primary': '#1a2318',
            '--bg-secondary': '#243022',
            '--bg-sidebar': '#121a10',
            '--bg-titlebar': '#2d3f2a',
            '--bg-statusbar': '#344d30',
            '--bg-hover': '#2d3f2a',
            '--bg-active': '#344d30',
            '--border': '#344d30',
            '--text-primary': '#d4e6c3',
            '--text-secondary': '#6b8f5e',
            '--text-dim': '#4a6640',
            '--text-sidebar': '#d4e6c3',
            '--text-active': '#e8f5d8',
            '--line-number': '#4a6640',
            '--cursor': '#d4e6c3',
            '--selection': '#344d30',
            '--accent': '#7ec850',
            '--accent-hover': '#6ab840',
            '--scrollbar': '#344d30',
            '--scrollbar-hover': '#4a6640',
        },
    },
    {
        id: 'ocean',
        name: 'Ocean',
        isDark: true,
        vars: {
            '--bg-primary': '#0f1e2e',
            '--bg-secondary': '#162739',
            '--bg-sidebar': '#0a1622',
            '--bg-titlebar': '#1d3147',
            '--bg-statusbar': '#1d3147',
            '--bg-hover': '#1d3147',
            '--bg-active': '#264058',
            '--border': '#1d3147',
            '--text-primary': '#b8c5d4',
            '--text-secondary': '#5a7088',
            '--text-dim': '#3e5468',
            '--text-sidebar': '#b8c5d4',
            '--text-active': '#d4dde8',
            '--line-number': '#3e5468',
            '--cursor': '#b8c5d4',
            '--selection': '#1d3147',
            '--accent': '#7eb8c4',
            '--accent-hover': '#6aa6b4',
            '--scrollbar': '#1d3147',
            '--scrollbar-hover': '#264058',
        },
    },
    {
        id: 'slate',
        name: 'Slate',
        isDark: true,
        vars: {
            '--bg-primary': '#1c2128',
            '--bg-secondary': '#22272e',
            '--bg-sidebar': '#171b21',
            '--bg-titlebar': '#2d333b',
            '--bg-statusbar': '#373e47',
            '--bg-hover': '#2d333b',
            '--bg-active': '#373e47',
            '--border': '#373e47',
            '--text-primary': '#adbac7',
            '--text-secondary': '#636e7b',
            '--text-dim': '#4a525c',
            '--text-sidebar': '#adbac7',
            '--text-active': '#cdd9e5',
            '--line-number': '#4a525c',
            '--cursor': '#adbac7',
            '--selection': '#2d333b',
            '--accent': '#6cb6ff',
            '--accent-hover': '#5aa3eb',
            '--scrollbar': '#373e47',
            '--scrollbar-hover': '#444c56',
        },
    },
    {
        id: 'sage',
        name: 'Sage',
        isDark: true,
        vars: {
            '--bg-primary': '#1e2420',
            '--bg-secondary': '#262d28',
            '--bg-sidebar': '#181c1a',
            '--bg-titlebar': '#2f3833',
            '--bg-statusbar': '#3a4540',
            '--bg-hover': '#2f3833',
            '--bg-active': '#3a4540',
            '--border': '#3a4540',
            '--text-primary': '#b8c4ba',
            '--text-secondary': '#6a7a6e',
            '--text-dim': '#4d5a51',
            '--text-sidebar': '#b8c4ba',
            '--text-active': '#cdd6cf',
            '--line-number': '#4d5a51',
            '--cursor': '#b8c4ba',
            '--selection': '#3a4540',
            '--accent': '#8fbc94',
            '--accent-hover': '#7eaa83',
            '--scrollbar': '#3a4540',
            '--scrollbar-hover': '#4a574f',
        },
    },
    {
        id: 'twilight',
        name: 'Twilight',
        isDark: true,
        vars: {
            '--bg-primary': '#1b1d2b',
            '--bg-secondary': '#222536',
            '--bg-sidebar': '#161823',
            '--bg-titlebar': '#2a2e42',
            '--bg-statusbar': '#343852',
            '--bg-hover': '#2a2e42',
            '--bg-active': '#343852',
            '--border': '#343852',
            '--text-primary': '#bcc2d4',
            '--text-secondary': '#666c84',
            '--text-dim': '#494e63',
            '--text-sidebar': '#bcc2d4',
            '--text-active': '#d4d9e8',
            '--line-number': '#494e63',
            '--cursor': '#bcc2d4',
            '--selection': '#343852',
            '--accent': '#8a9bd6',
            '--accent-hover': '#7689c8',
            '--scrollbar': '#343852',
            '--scrollbar-hover': '#42476a',
        },
    },
    {
        id: 'mocha',
        name: 'Mocha',
        isDark: true,
        vars: {
            '--bg-primary': '#22201d',
            '--bg-secondary': '#2a2724',
            '--bg-sidebar': '#1b1916',
            '--bg-titlebar': '#34302c',
            '--bg-statusbar': '#3f3a35',
            '--bg-hover': '#34302c',
            '--bg-active': '#3f3a35',
            '--border': '#3f3a35',
            '--text-primary': '#c4bcb0',
            '--text-secondary': '#7a7165',
            '--text-dim': '#574f46',
            '--text-sidebar': '#c4bcb0',
            '--text-active': '#d8d0c4',
            '--line-number': '#574f46',
            '--cursor': '#c4bcb0',
            '--selection': '#3f3a35',
            '--accent': '#a89878',
            '--accent-hover': '#988868',
            '--scrollbar': '#3f3a35',
            '--scrollbar-hover': '#4f4942',
        },
    },
];

export const DEFAULT_THEME_ID = 'default-dark';

export function getTheme(id: string): Theme {
    return themes.find((t) => t.id === id) ?? themes[0];
}
